## School Level Results

Of most interest to states for reporting and accountability purposes is how well skip-year growth and one-year growth compare when aggregated to the school level. Aggregating SGPs is usually accomplished by taking the median or mean of the SGPs for the students attending a school for a given year and content area. One critical difference of skip-year growth from one-year growth is the absence of SGPs for 4<sup>th</sup> grade students. A school serving 4<sup>th</sup> graders would have growth for those students when using one-year growth but not with skip-year growth. Elementary schools comprising grades K-5 or K-6 would have between a third and a half of their students without skip-year growth when they previously had one-year growth.

Although the *total* impact on school growth is important in determining the best path forward for the state's accountability decisions, including 4<sup>th</sup> grade growth in *only* one-year analyses leads to additional school level disparities beyond those resulting from the use of different analytic methods.  The results are thus summarized in two ways:

1. Aggregates were calculated using all available skip-year and one-year growth scores.
2. Aggregates were calculated including only grades/content areas for which *both* skip-year and one-year growth could be calculated.

\noindent The first method includes all available growth scores (either skip-year or one-year) and calculates the mean and standard deviation from those. This method would include 4<sup>th</sup> grade one-year SGPs for schools but those same schools would not have skip-year growth for those students. The second method filters students to only those in grades/content areas in which growth could be calculated in both analyses. This method omits 4<sup>th</sup> graders since they do not have a skip-year SGP.


```{r, cache=TRUE, echo=FALSE, include=FALSE, School_Lev_Values}
##  Calculate Differences if not already done
	Report_Data[, DIFF := as.numeric(NA)]
	Report_Data[, DIFF := SGP - NO_SKIP_SGP]
	Report_Data[, ABS_DIFF := as.numeric(NA)]
	Report_Data[, ABS_DIFF := abs(SGP - NO_SKIP_SGP)]

##  Calculate School Level Values
	sch_msgp <- Report_Data[VALID_CASE=='VALID_CASE' & YEAR == "2019" & !is.na(SCHOOL_NUMBER),
  		            list(
      			          MEAN_NO_SKIP_SGP = mean(NO_SKIP_SGP, na.rm = TRUE),
            			    MEAN_SKIP_SGP = mean(SGP, na.rm = TRUE),
			                MEAN_SCALE_SCORE_PRIOR_STANDARDIZED = mean(SCALE_SCORE_PRIOR_STANDARDIZED, na.rm=TRUE),
      				        MEAN_NO_SKIP_SGP_SCALE_SCORE_PRIOR_STANDARDIZED = mean(NO_SKIP_SGP_SCALE_SCORE_PRIOR_STANDARDIZED, na.rm=TRUE),
              			  COUNT_NO_SKIP_SGP = sum(!is.na(NO_SKIP_SGP)),
			                COUNT_SKIP_SGP = sum(!is.na(SGP)),
      			          COUNT_TOTAL = .N),
            			  keyby = c("CONTENT_AREA", "SCHOOL_NUMBER")][,DIFFERENCE_SKIP_NO_SKIP_MEAN_SGP:=round(abs(MEAN_SKIP_SGP-MEAN_NO_SKIP_SGP), 2)]

	sch_msgp_x <- Report_Data[VALID_CASE=='VALID_CASE' & YEAR == "2019" & !is.na(SCHOOL_NUMBER) & GRADE %in% params$skip.grades,
  			            list(
        				        MEAN_NO_SKIP_SGP = mean(NO_SKIP_SGP, na.rm = TRUE),
                				MEAN_SKIP_SGP = mean(SGP, na.rm = TRUE),
				                MEAN_SCALE_SCORE_PRIOR_STANDARDIZED = mean(SCALE_SCORE_PRIOR_STANDARDIZED, na.rm=TRUE),
        				        MEAN_NO_SKIP_SGP_SCALE_SCORE_PRIOR_STANDARDIZED = mean(NO_SKIP_SGP_SCALE_SCORE_PRIOR_STANDARDIZED, na.rm=TRUE),
                				COUNT_NO_SKIP_SGP = sum(!is.na(NO_SKIP_SGP)),
				                COUNT_SKIP_SGP = sum(!is.na(SGP)),
        				        COUNT_TOTAL = .N),
              				keyby = c("CONTENT_AREA", "SCHOOL_NUMBER")][,DIFFERENCE_SKIP_NO_SKIP_MEAN_SGP:=round(abs(MEAN_SKIP_SGP-MEAN_NO_SKIP_SGP), 2)]

##  Calculate School Level Summaries
	sch_stat <- sch_msgp[COUNT_NO_SKIP_SGP > 9 & COUNT_SKIP_SGP > 9, list(
	    Mean_Sequential = round(mean(MEAN_NO_SKIP_SGP, na.rm=TRUE), 1),
  	  SD_Sequential = round(sd(MEAN_NO_SKIP_SGP, na.rm=TRUE), 1),
    	Corr_Sequential = round(cor(MEAN_NO_SKIP_SGP, MEAN_NO_SKIP_SGP_SCALE_SCORE_PRIOR_STANDARDIZED, use="complete.obs"), 2),
    	N_Sequential = sum(!is.na(MEAN_NO_SKIP_SGP)),
  	  Mean_Skip = round(mean(MEAN_SKIP_SGP, na.rm=TRUE), 1),
	    SD_Skip = round(sd(MEAN_SKIP_SGP, na.rm=TRUE), 1),
    	Corr_Skip = round(cor(MEAN_SKIP_SGP, MEAN_SCALE_SCORE_PRIOR_STANDARDIZED, use="complete.obs"), 2),
  	  N_Skip = sum(!is.na(MEAN_SKIP_SGP))), keyby = c("CONTENT_AREA")]
	sch_cor <- sch_msgp[COUNT_NO_SKIP_SGP > 9 & COUNT_SKIP_SGP > 9, list(
  	  Skip_x_Sequential = round(cor(MEAN_NO_SKIP_SGP, MEAN_SKIP_SGP, use="complete.obs"), 2), N = .N), keyby = c("CONTENT_AREA")]
	sch_diff <- sch_msgp[COUNT_NO_SKIP_SGP > 9 & COUNT_SKIP_SGP > 9, list(
			`Median Difference` = round(median(DIFFERENCE_SKIP_NO_SKIP_MEAN_SGP, na.rm=TRUE), 2),
			`95%ile Difference`=round(quantile(DIFFERENCE_SKIP_NO_SKIP_MEAN_SGP, probs=0.95, na.rm=TRUE), 2), N = .N), keyby = c("CONTENT_AREA")]

	sch_stat_x <- sch_msgp_x[COUNT_NO_SKIP_SGP > 9 & COUNT_SKIP_SGP > 9, list(
  	  Mean_Sequential = round(mean(MEAN_NO_SKIP_SGP, na.rm=TRUE), 1),
    	SD_Sequential = round(sd(MEAN_NO_SKIP_SGP, na.rm=TRUE), 1),
	    Corr_Sequential = round(cor(MEAN_NO_SKIP_SGP, MEAN_NO_SKIP_SGP_SCALE_SCORE_PRIOR_STANDARDIZED, use="complete.obs"), 2),
    	N_Sequential = sum(!is.na(MEAN_NO_SKIP_SGP)),
  	  Mean_Skip = round(mean(MEAN_SKIP_SGP, na.rm=TRUE), 1),
	    SD_Skip = round(sd(MEAN_SKIP_SGP, na.rm=TRUE), 1),
    	Corr_Skip = round(cor(MEAN_SKIP_SGP, MEAN_SCALE_SCORE_PRIOR_STANDARDIZED, use="complete.obs"), 2),
  	  N_Skip = sum(!is.na(MEAN_SKIP_SGP))), keyby = c("CONTENT_AREA")]
	sch_cor_x <- sch_msgp_x[COUNT_NO_SKIP_SGP > 9 & COUNT_SKIP_SGP > 9, list(
  	  Skip_x_Sequential = round(cor(MEAN_NO_SKIP_SGP, MEAN_SKIP_SGP, use="complete.obs"), 2), N = .N), keyby = c("CONTENT_AREA")]
	sch_diff_x <- sch_msgp_x[COUNT_NO_SKIP_SGP > 9 & COUNT_SKIP_SGP > 9, list(
			`Median Difference` = round(median(DIFFERENCE_SKIP_NO_SKIP_MEAN_SGP, na.rm=TRUE), 2),
			`95%ile Difference`=round(quantile(DIFFERENCE_SKIP_NO_SKIP_MEAN_SGP, probs=0.95, na.rm=TRUE), 2), N = .N), keyby = c("CONTENT_AREA")]

	n.schools <- prettyNum(roundUp(length(unique(sch_msgp$SCHOOL_NUMBER))), big.mark=',')

##  Executive Summary figures/stats
	# At the school level there is, again not surprisingly, a very high correlation (~ 0.9)
	exec.sch.correlate <- sch_msgp[, list(cor(MEAN_SKIP_SGP, MEAN_NO_SKIP_SGP, use="complete.obs"))] # , keyby=c("CONTENT_AREA")
	# the high correlation does mask approximately X percent of the schools whose mean/median SGP differs by X or more.
	exec.sch.quantiles <- sch_msgp[, as.list(quantile(DIFFERENCE_SKIP_NO_SKIP_MEAN_SGP, probs=(1:19)/20, na.rm=TRUE)), keyby=c("CONTENT_AREA")]

```
