
```{r, echo=FALSE, include=FALSE}
  tmp_env <- environment()
  if(bindingIsLocked("params", env = tmp_env)) unlockBinding("params", env = tmp_env)

  ###
	###   Lists of state specific variables included in the report.
	###

  ###   Working Directory
  if (is.null(params$working.directory)) {
    if (!is.null(knitr::opts_knit$get("output.dir"))) {
      params$working.directory <- knitr::opts_knit$get("output.dir")
    } else params$working.directory <- getwd()
  }

  ###   Draft
  # draft.text <- "\\vspace{16pt} \\noindent  \\textbf{FOR INTERNAL USE ONLY - DO NOT CIRCULATE!} \\vspace{20pt}"
  if (is.null(params$draft.text)) {
    params$draft.text <- ""
  }
  if (params$draft.text != "") {
    if (!grepl("[\\]|[<]", params$draft.text)) {
      params$draft.text <- paste0("\\vspace{16pt} \\noindent  \\textbf{", params$draft.text, "} \\vspace{20pt}")
    }
  }

  ###   State name and education organization
  if (is.null(params$state.abv)) {
    if (is.null(params$state.name)) stop("State name or abbreviation parameter (state.name or state.abv) must be provided at a minimum!")
    tmp.state.abv <- params$state.abv <- datasets::state.abb[datasets::state.name == params$state.name] # getStateAbbreviation(params$state.name, type="Abbreviation") # Doesn't work in all cases...
  } else tmp.state.abv <- params$state.abv[[1]]
  if (is.null(params$state.name)) {
    if (is.null(params$state.abv)) stop("State name or abbreviation parameter (state.name or state.abv) must be provided at a minimum!")
    tmp.state.name <- params$state.name <- SGP::getStateAbbreviation(tmp.state.abv, type="state")
  } else tmp.state.name <- params$state.name[[1]]

  if (is.null(params$state.org)) {
    # unlockBinding("params", env = .GlobalEnv)
    params$state.org <- SGPstateData[[tmp.state.abv]][["Assessment_Program_Information"]][["Organization"]][["Name"]]
  }
  if (is.null(params$state.org.abv)) {
    params$state.org.abv <- SGPstateData[[tmp.state.abv]][["Assessment_Program_Information"]][["Organization"]][["Abbreviation"]]
  }

  if (is.null(params$test.name)) {
    params$test.name <- SGPstateData[[tmp.state.abv]][["Assessment_Program_Information"]][["Assessment_Name"]]
  }
  if (is.null(params$test.abv)) {
    params$test.abv <- SGPstateData[[tmp.state.abv]][["Assessment_Program_Information"]][["Assessment_Abbreviation"]]
  }

  ###   Content areas
  if (is.null(params$GL_subjects)) {
    params$GL_subjects <- unique(Report_Data[!is.na(SGP) & GRADE != "EOCT", CONTENT_AREA])
  }
  params$GL_camel <- sapply(params$GL_subjects, capwords) # sub("ela", "ELA", tolower(params$GL_subjects))
  params$GL_text <- paste(paste(head(params$GL_camel, -1), collapse=", "), tail(params$GL_camel, 1), sep=" and ") # sub("ela", "ELA", tolower(params$GL_text))
  params$GL_text_long <- sub("ELA", "English language arts (ELA)", params$GL_text) # "English language arts (ELA) and mathematics"

  if (is.null(params$EOC_subjects)) {
    params$EOC_subjects <- unique(Report_Data[!is.na(SGP) & GRADE == "EOCT", CONTENT_AREA])
  }
  if (length(params$EOC_subjects > 0)) {
    params$eoct.tf <- FALSE
    params$EOC_subjects <- NULL
  } else  params$eoct.tf <- TRUE

  params$subject_order <- c(params$GL_subjects, params$EOC_subjects)

  ###   Grades
  if (is.null(params$seq.grades)) {
    params$seq.grades <- unique(Report_Data[!is.na(NO_SKIP_SGP), GRADE])
  }
  if (is.null(params$skip.grades)) {
    params$skip.grades <- unique(Report_Data[!is.na(SGP), GRADE])
  }

  ###   Normalize Child and GoFit plot paths
  if (!is.null(params$child.directory)|!is.null(params$gof.path.seq)|!is.null(params$gof.path.skip)) {
    tmp.wd <- getwd()
    setwd(params$working.directory)
    if (!is.null(params$child.directory)) {
      params$child.directory <- normalizePath(params$child.directory[[1]]) # need the '[[1]]' to knit to .Rmd for testing/editing
    }
    if (!is.null(params$gof.path.seq)) {
      params$gof.path.seq <- normalizePath(params$gof.path.seq[[1]])
    }
    if (!is.null(params$gof.path.skip)) {
      params$gof.path.skip <- normalizePath(params$gof.path.skip[[1]])
    }
    setwd(tmp.wd)
  }

```


```{r, echo=FALSE, include=FALSE}
  ## set a universal Cache path
  knitr::opts_chunk$set(cache.path = "assets/_cache/Skip_Year_Report")

  knitted_hooks_2 <- knitr::knit_hooks$get(c('source', 'output', 'document'))
  save(knitted_hooks_2, file=file.path(params$working.directory, "knitted_hooks_2.rdb"))
  # multdoc.call <- match.call()
  # argg <- c(as.list(environment()), list(...))
  # save(list=c('matched.call', 'argg'), file=file.path(params$working.directory, "Call_Matches_Knitted.rdb"))
  # rmarkdown.pandoc.to.multdoc <- knitr::opts_knit$get('rmarkdown.pandoc.to')
  # html.tf1 <- knitr::is_html_output()
  # html.tf2 <- knitr::is_html_output(excludes = "markdown")
  # save(list=c('rmarkdown.pandoc.to.multdoc', 'html.tf1', 'html.tf2'), file="rmarkdown_pandoc_to_multdoc.rdb")

  ##  Load some R packages and functions required for HTML table creation silently.
  ##  Load SGP and other packages here to avoid messages.
  require(SGP)
	require(data.table)
  require(stringr)
	require(Gmisc)
  require(htmlTable)
	require(ggplot2)

  ##  Set Table, Figure and Equation Counters
  setCounters()
	options(fig_caption_no_sprintf = "**Figure %d:** %s")
	options("fig_caption_no_roman"=FALSE)

  ##  Create assets and/or img directories if doesn't exist
  if (!dir.exists(file.path(params$working.directory, "assets", "img"))) {
    dir.create(file.path(params$working.directory, "assets", "img"), showWarnings = FALSE, recursive = TRUE)
  }

  if (!dir.exists(file.path(params$working.directory, "assets", "tables"))) {
    dir.create(file.path(params$working.directory, "assets", "tables"), showWarnings = FALSE, recursive = TRUE)
  }

  ### Utility function - Assumes first two "levels" are the main dichotomy
  percent_demog <- function(demog) {
  	return(100*as.numeric(table(demog)[2])/as.numeric(sum(table(demog)[1:2])))
  }

  roundUp <- function(x, to=50) to*(x%/%to + as.logical(x%%to))

  if (!packageVersion("Literasee") > '0.0.4.96')  {
    source("https://gist.githubusercontent.com/hack-r/22104543e2151519c41a8f0ce042b31c/raw/01731f3176b4ee471785639533d38eda4790ab77/numbers2words.r")
  }

```
