---
title: "Demonstration Skip Year SGP Analyses"
subtitle: "A Historical Comparison of the 2019 SGP Results"
author:
  - name: Damian W. Betebenner
  - name: Adam R. VanIwaarden
organization:
  - name: National Center for the Improvement
  - name: of Educational Assessment (NCIEA)
---

<!--  Set up report params, packages, cache, etc.  -->
<!--  NOTE: need the '[[1]]' in child.file.path to knit to .Rmd for testing/draft editing  -->

```{r setup, child = file.path(params$child.file.path[[1]], "report_setup.Rmd"), eval=TRUE}
```


<!--SGPreport-->

<!--
This document was written by Damian Betebenner & Adam VanIwaarden for the Demonstration Department of Education.

	Original Draft:  September 8, 2020
	Final Draft:     February 15, 2021
-->


<!--  Executive Summary - wrapped in YAML (keep line between this comment and next R chunk!) -->

```{r ExecSummary, child = file.path(params$child.file.path, "Executive_Summary.Rmd"), eval=TRUE}
```

<!--  1. Background  -->
```{r Background, child = file.path(params$child.file.path, "Background.Rmd"), eval=TRUE}
```


<!--  2. Data  -->
```{r Data, child = file.path(params$child.file.path, "Data_1_intro.Rmd"), eval=TRUE}
```

```{r Data_count_table, child = file.path(params$child.file.path, "Data_2_counts_table.Rmd"), eval=TRUE}
```

```{r Data_summary, child = file.path(params$child.file.path, "Data_3_summary.Rmd"), eval=TRUE}
```


<!--  3. Analyses and Results  -->
```{r AR_1, child = file.path(params$child.file.path, "Analyses_Results_1_intro.Rmd"), eval=TRUE}
```

<!--     3.1  Individual Results  -->
```{r AR_Indiv_Results_1, child = file.path(params$child.file.path, "Analyses_Results__Indiv_Corrs_and_Stats.Rmd"), eval=TRUE}
```

```{r AR_Indiv_Results_2, child = file.path(params$child.file.path, "Analyses_Results__Indiv_Summary.Rmd"), eval=TRUE}
```

<!--     3.2  School Results  -->
```{r AR_School_Results_1, child = file.path(params$child.file.path, "Analyses_Results__School_1_Intro.Rmd"), eval=TRUE}
```

```{r AR_School_Results_2, child = file.path(params$child.file.path, "Analyses_Results__School_Corrs_and_Stats.Rmd"), eval=TRUE}
```

<!--        3.2.1  School Results - School mean SGP correlations -->
```{r AR_School_Results_3, child = file.path(params$child.file.path, "Analyses_Results__School_MSGP_Corrs.Rmd"), eval=TRUE}
```

<!--        3.2.2  School Results - School mean SGP differences -->
```{r AR_School_Results_4, child = file.path(params$child.file.path, "Analyses_Results__School_MSGP_Diffs.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, results="asis", echo=FALSE}
	pageBreak()
```


<!--     3.3  Demographic Group Results  -->
```{r, cache=FALSE, echo=FALSE, include=FALSE}
  ###   Any necessary state-specific data formatting and variable creation - DON'T CACHE!!!

  ##  Calculate School Demographic percentages if not already done
	Report_Data[, PCT_SCHOOL_FRL := percent_demog(FREE_REDUCED_LUNCH_STATUS), by = c("YEAR", "CONTENT_AREA", "GRADE", "SCHOOL_NUMBER")]
	Report_Data[, PCT_SCHOOL_ELL := percent_demog(ELL_STATUS), by = c("YEAR", "CONTENT_AREA", "GRADE", "SCHOOL_NUMBER")]
  Report_Data[, PCT_SCHOOL_SWD := percent_demog(IEP_STATUS), by = c("YEAR", "CONTENT_AREA", "GRADE", "SCHOOL_NUMBER")]
```


```{r, cache=FALSE, echo=FALSE}
  ##  Demographic percentage chunk to evaluate in creation of sch_demog_msgp summary table (see Analyses_Results__Demographic_Groups_Intro_and_Calcs.Rmd)
  ##  Assumes the "PCT_SCHOOL_*" convention

  vars.to.get <- grep("PCT_SCHOOL_", names(Report_Data), value=TRUE)
  smry_eval_expression <- paste0(sub("PCT_SCHOOL_", "PERCENT_", vars.to.get), " = ", vars.to.get, "[1]")

  demog.group.count <- 3
  demog.group.description <-
    "economically disadvantaged students (as indicated by free/reduced-price lunch eligibility status), English language learners, and students with disabilities (as indicated by having an individualized education program - IEP)."
```
```{r AR_Demog_Results_1, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Groups_Intro_and_Calcs.Rmd"), eval=TRUE}
```


<!--        3.3.1  Demographic Results - Economic Disadvantaged (FRL) -->
```{r, cache=FALSE, echo=FALSE}
  # demog.group <- as.list(unlist(params[["demographic"]][["value"]][["economic_status"]])) # doesn't work with params...
  demog.group <- list(
    name = "Economically Disadvantaged Students",
    label = "FRL",
    variable = "FREE_REDUCED_LUNCH_STATUS",
    school.variable = "PERCENT_FRL")

  demog.group[["description"]] <- "eligible for free/reduced lunch, or FRL"
	demog.group[["count.comment"]] <- "As the results show, there is not a considerable difference between the two groups' growth calculation rates under either analysis."
```
```{r AR_Demog_Results_2a, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_1_Counts.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, echo=FALSE}
	demog.group[["student.stat.comment"]] <- "The results show there is not a considerable difference *within* the two groups' growth under either analysis.  The two growth measures are highly correlated and have similar distributional qualities within each group by content area.  However, it is important to note the growth gap *between* the FRL/non-FRL groups in both ELA and Mathematics.  This gap is approximately 7-10 points, on average, for FRL students for the sequential SGP estimates, and increases to roughly 11-15 points using the skip-year estimates."
```
```{r AR_Demog_Results_2b, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_2_Student_Corrs_Stats.Rmd"), eval=TRUE}
```

<!--             3.3.1  Schools -->
```{r, cache=FALSE, echo=FALSE}
  demog.group[["school.cor.comment"]] <- "The results show a negative relationship (correlation) between typical school growth and the school percentage of FRL students. That is, the schools with larger FRL populations tend to demonstrate lower academic growth."
```
```{r AR_Demog_Results_2c, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_3_School_Corrs_Stats.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, echo=FALSE}
	demog.group[["school.diff.comment"]] <- "This plot shows a slight negative relationship between the MSGP difference and FRL population size. This suggests that, on average, schools with higher FRL populations have lower difference values (i.e. schools with larger FRL populations may be slightly more likely to be negatively impacted with the use of skip-year analysis)."
```
```{r AR_Demog_Results_2d, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_4_Diffs.Rmd"), eval=TRUE}
```


<!--        3.3.2  Demographic Results - English Language Learners (ELL) -->
```{r, cache=FALSE, echo=FALSE}
  demog.group <- list(
    name = "English Language Learners",
    label = "ELL",
    variable = "ELL_STATUS",
    school.variable = "PERCENT_ELL")

  # demog.group[["description"]] <- "defined as ..."
	demog.group[["count.comment"]] <- paste("As the results show, there is not a considerable difference between the two groups' growth calculation rates under either analysis.  However, roughly 10% fewer students receive a SGP calculation under the skip-year approach.")
```
```{r AR_Demog_Results_3a, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_1_Counts.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, echo=FALSE}
	demog.group[["student.stat.comment"]] <- "The two growth measures are highly correlated and have similar distributional qualities within each group by content area.  There is a slight difference *within* the ELL group's growth calculation between the sequential and skip-year analyses. This results in increasing the otherwise modest growth gap between ELL and non-ELL students in Mathematics between the sequential and skip-year analyses."
```
```{r AR_Demog_Results_3b, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_2_Student_Corrs_Stats.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, echo=FALSE}
  demog.group[["school.cor.comment"]] <- "As the results show, the relationship (correlation) between mean growth and the school percentage of ELL students is moderately negative."
```
```{r AR_Demog_Results_3c, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_3_School_Corrs_Stats.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, echo=FALSE}
	demog.group[["school.diff.comment"]] <- "This plot shows a slightly negative relationship between the MSGP difference and ELL population size for the skip-year subset, particularly in Reading.  This suggests that, on average, schools with higher ELL populations have lower difference values in Reading (i.e. schools with larger ELL populations are slightly more likely to be negatively impacted with the use of skip-year analysis, although this impact appears to modest)."
```
```{r AR_Demog_Results_3d, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_4_Diffs.Rmd"), eval=TRUE}
```


<!--        3.3.3  Demographic Results - Students with Disabilities (SWD) -->
```{r, cache=FALSE, echo=FALSE}
  demog.group <- list(
    name = "Students with Disabilities",
    label = "SWD",
    variable = "IEP_STATUS",
    school.variable = "PERCENT_SWD")

  demog.group[["description"]] <- "or SWD, indicated as having an IEP"
	demog.group[["count.comment"]] <- "As the results show, there is not a considerable difference between the two groups' growth calculation rates under either analysis, although students with disabilities (SWD) do receive SGP estimates at slightly lower rate than those without."
```
```{r AR_Demog_Results_4a, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_1_Counts.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, echo=FALSE}
	demog.group[["student.stat.comment"]] <- "The results show that the two growth measures are highly correlated and have similar distributional qualities within each group by content area.  There is a slight difference *within* the SWD group's MSGPs between the sequential and skip-year analyses.  Specifically, this group's typical growth in both ELA and Mathematics are 1-3 points lower using the skip-year analysis, thus increasing the existing growth gap between SWD and non-SWD populations. The gap is 7 points, on average, for the sequential SGP estimates, and increases slightly to approximately 9 points using the skip-year estimates."
```
```{r AR_Demog_Results_4b, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_2_Student_Corrs_Stats.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, echo=FALSE}
  demog.group[["school.cor.comment"]] <- "As the results show, a negative relationship (correlation) exists between typical school growth and the school SWD percentage.  That is, the schools with larger populations of students with disabilities tend to demonstrate lower academic growth."
```
```{r AR_Demog_Results_4c, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_3_School_Corrs_Stats.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, echo=FALSE}
	demog.group[["school.diff.comment"]] <- "The plots show slight negative relationships between MSGP difference and SWD population size for the skip-year subset.  This suggests that, on average, schools with higher SWD populations have lower difference values (i.e. schools with larger SWD populations are slightly more likely to be negatively impacted with the use of skip-year analysis).  Note that the range of school percent SWD is restricted to 0 to 25%."

  demog.group[["school.variable"]] <- "PERCENT_SWD"
```
```{r AR_Demog_Results_4d, child = file.path(params$child.file.path, "Analyses_Results__Demographic_Subgroup_4_Diffs.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, results="asis", echo=FALSE}
	pageBreak()
```


<!--  4. Summary  -->
```{r Summary, child = file.path(params$child.file.path, "Summary.Rmd"), eval=TRUE}
```

```{r, cache=FALSE, results="asis", echo=FALSE}
	pageBreak()
```


<!--  References  -->

# References {-}
::: {#refs}
:::


<!--  Appendices - Initialize appendix format: re-start counters and change to alphabetical (A) -->
```{r, cache=FALSE, results="asis", echo=FALSE}
	pageBreak()
  startAppendix()
```

<!--     Appendix A. - Intro -->
```{r Appendix, child = file.path(params$child.file.path, "Appendix_A_Intro.Rmd"), eval=TRUE}
```

<!--        Appendix A. - Sequential Only Analyses -->
```{r Appendix, child = file.path(params$child.file.path, "Appendix_A_Sequential_Only.Rmd"), eval=TRUE}
```

<!--        Appendix A. - Grade Level ELA and Mathematics -->
```{r Appendix, child = file.path(params$child.file.path, "Appendix_A_Grade_Level.Rmd"), eval=TRUE}
```

<!--  Appendices - End appendix format: re-start counters and change back to numeric for subsequent re-rendering -->
```{r, cache=FALSE, results="asis", echo=FALSE}
	endAppendix()
```
